-- CreateEnum
CREATE TYPE "StatusNfe" AS ENUM ('PENDENTE', 'AUTORIZADA', 'CANCELADA', 'REJEITADA');

-- AlterTable
ALTER TABLE "Venda" ADD COLUMN     "dataEmissaoNfe" TIMESTAMP(3),
ADD COLUMN     "desconto" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "frete" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "observacoes" VARCHAR(500),
ADD COLUMN     "outrasDespesas" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "seguro" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "serieNota" VARCHAR(10),
ADD COLUMN     "statusNfe" "StatusNfe" NOT NULL DEFAULT 'PENDENTE';
