-- AlterTable
ALTER TABLE "Produto" ALTER COLUMN "estoque" SET DEFAULT 0,
ALTER COLUMN "estoque" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "VendaItem" ALTER COLUMN "quantidade" SET DATA TYPE DOUBLE PRECISION;
