-- AlterTable
ALTER TABLE "Venda" ADD COLUMN "custoTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Venda" ADD COLUMN "lucro" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "VendaItem" ADD COLUMN "custoUnitario" DOUBLE PRECISION NOT NULL DEFAULT 0;
